### ISSUE TITLE
Plan for future Maven Repository on jetty.org

### ISSUE THREAD

**Issue by joakime** [jetty/jetty.website#15]
Once jetty.org goes live we should start migrating our existing oss.sonatype.org support to something on jetty.org.

We currently have the following on oss.sonatype.org 

* Release Repo - https://oss.sonatype.org/content/repositories/jetty-releases/
* Snapshots Repo - https://oss.sonatype.org/content/repositories/jetty-snapshots/
* Staging Support - https://oss.sonatype.org/content/repositories/jetty-####/ (these are dynamically assigned and temporary)
* Composite Repo of Releases & Staging - https://oss.sonatype.org/content/groups/jetty-with-staging/

There has been an effort on oss.sonatype.org to wind down some of the hosting of snapshots (and the like) on their platform.

I propose we move all of the content from `jetty-releases` and `jetty-snapshots` to jetty.org (on some URL path that we should attempt to specify in this issue).
Ideally it would be great if we can even install Nexus (with staging support) on jetty.org as well.
Bonus if we can get that nexus blessed by oss.sonatype.org to allow promotion of releases through to maven central.

**Comment by joakime** [comment]
Sonatype.org published a deprecation notice recently - https://central.sonatype.org/news/20240109_issues_sonatype_org_deprecation/

**Comment by olamy** [comment]
The new service is now here https://s01.oss.sonatype.org/.  
oss.s.o is deprecated now but no announcement yet of end of support for this.
We can host snapshots or mirror staging from https://s01.oss.sonatype.org or oss.s.o. (we can simply proxy our internal nexus?)

But release I really have high doubt (no chance) Sonatype will accept syncing from our nexus....
I can still ask but....

**Comment by jmcc0nn3ll** [comment]
Any updates on this?

**Comment by olamy** [comment]
We have nothing to do. the depreciation notice is related to issues.sonatype.org not about oss.sonatype.org
