### ISSUE TITLE
Final Steps

### ISSUE THREAD

**Issue by jmcc0nn3ll** [jetty/jetty.website#23]
As we are heading into the deployment of the jetty.org site, I wanted to open this issue to identify and track the final steps we need to take. AFAICT

- [x] Resolve #21 with the rewrite handler on jetty.org
- [x] Check in with Eclipse IP about repo transfer
- [x] Migrate this jetty.website to the jetty GitHub organization
- [x] Sort out where to publish a ui-bundle artifact
- [x] Find and wire up contribution guide
- [x] api.jetty.org -> javadoc.jetty.org (update cert, fix jetty setup, populate with @olamy javadoc repo)
- [ ] #45
- [x] Push the build results into the jetty.org static site on our amazon webtide.com property
- [x] Notify Eclipse to place a 301 redirect on eclipse.dev/jetty

Anything else?

**Comment by jmcc0nn3ll** [comment]
@olamy can you set up a build for this repository? We'll need to change it a bit when we move this repository to the jetty organization but we should test it out now

**Comment by jmcc0nn3ll** [comment]
Issue for coordinating with Eclipse on the redirect: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4602

**Comment by mojavelinux** [comment]
> Set up a Github Action to build this repository with Maven and jenkins.webtide.net.

The command you need to run can be found in the current GitHub Actions workflow. See

https://github.com/webtide/jetty.website/blob/main/.github/workflows/publish-site.yml#L47-L52

Note that the ANTORA_CACHE_DIR environment variable is required for the time being.

**Comment by mojavelinux** [comment]
There is something missing from the list. You will need a build to produce and publish the UI bundle. An alternative is to build the UI bundle in the same job that generates the site. In other words, produce the UI bundle from source each time the site is generated. There's nothing wrong with that, though it makes it harder to test the site locally since there is no UI bundle at a publicly accessible URL.

**Comment by jmcc0nn3ll** [comment]
Eclipse IP issue to make sure they are fine with transferring this over. https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14595

**Comment by jmcc0nn3ll** [comment]
Well, It would appear that transferring the repository is a non-starter, we can not give eclipsewebmaster access to our company organization. @mojavelinux are you ok with my just hooking up a remote to a repo in the jetty organization and transferring repo content over? We'll lose the issue history.

**Comment by joakime** [comment]
couldn't we (webtide) transfer this to github.com/jetty-project/ and then do the Eclipse IP from there to github.com/jetty/

**Comment by jmcc0nn3ll** [comment]
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4620#note_2245138

looks like we might get away with just rights to the repo itself.

**Comment by jmcc0nn3ll** [comment]
This repository has been moved to the jetty organization.

**Comment by jmcc0nn3ll** [comment]
Trying to sort out how to have the UI artifact published here now.

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4627

**Comment by mojavelinux** [comment]
This repository was set up with the understanding that we would be using GitHub. Switching to GitLab requires that the CI workflows be redeveloped. This is not a quick fix.

**Comment by jmcc0nn3ll** [comment]
Gitlab is not my intention at all; that is just where I have to interact with the Eclipse webmasters. The linked issue is my trying to sort out the organization secret deal/otterdog goop with them so we can publish the UI artifact here.

**Comment by mojavelinux** [comment]
My mistake. When you said "published here now" then linked to GitLab, my mind jumped to the fact that you were trying to do it on GitLab. I get it now.

**Comment by mojavelinux** [comment]
Are we still waiting on anything to merge the PRs with the migrated content?

**Comment by jmcc0nn3ll** [comment]
@sbordet ?

We just had to stage a release for 10 and 11 for a client, but I am personally not aware of anything else pending.

**Comment by jmcc0nn3ll** [comment]
@olamy pls populate /var/www/javadoc.jetty.org with the content you were working on

**Comment by olamy** [comment]
we might need more space on disk :)

**Comment by mojavelinux** [comment]
Hooray! :tada:  Congratulations on a successful migration!
