### ISSUE TITLE
Javadoc

### ISSUE THREAD

**Issue by jmcc0nn3ll** [jetty/jetty.website#24]
@mojavelinux was there a simple way to pull in javadoc into this antora site? We discussed it back in the beginning but I can't remember what the deal was

**Comment by jmcc0nn3ll** [comment]
I am checking with the others, but I think I'll probably just make a javadoc.jetty.org virtual host and dump all the versions we have a handy bundle for into that.

**Comment by joakime** [comment]
+1 for `javadoc.jetty.org`
bonus if we can manage it via a github repo (as static content).

**Comment by jmcc0nn3ll** [comment]
I need to change it from api.jetty.org to javadoc.jetty.org.

**Comment by jmcc0nn3ll** [comment]
it is javadoc.jetty.org and olivier is working to get the static repo handled, this issue can be closed
