### ISSUE TITLE
Example shows ContextHandlerCollection example that won't compile in 12.0.9

### ISSUE THREAD

**Issue by garydgregory** [jetty/jetty.website#29]
Hello,

The page https://eclipse.dev/jetty/documentation/jetty-12/programming-guide/index.html#pg-server-http-handler

shows the code fragment:
```
// Create a ContextHandlerCollection to hold contexts.
ContextHandlerCollection contextCollection = new ContextHandlerCollection();
```
But the class `org.eclipse.jetty.server.handler.ContextHandlerCollection` does not have a 0-arg constructor in 12.0.9.

**Comment by jmcc0nn3ll** [comment]
I take this one, but we are in the process of a major conversion to Antora on the mainline Jetty branches, so I'll make sure this is addressed after that lands.

**Comment by sbordet** [comment]
> But the class org.eclipse.jetty.server.handler.ContextHandlerCollection does not have a 0-arg constructor in 12.0.9.

`ContextHandlerCollection(ContextHandler... contexts)` should also work with no parameters.

@garydgregory are you sure?

**Comment by garydgregory** [comment]
@sbordet 
You're right! My IDE must have been complaining about somethings else. Sorry about that.
