### ISSUE TITLE
Consistency of left Menu vs right Contents

### ISSUE THREAD

**Issue by gregw** [jetty/jetty.website#30]
The website pages have either: a menu of the left board; a contents in the top right; or both.
Navigating the site can be confusing as the navigation mechanism pops from right to left and back again.

This could be made less confusing if the top level pages were more consistent in having both.

Specifically the home page https://jetty.github.io/jetty.website/ should to have a left Menu with the primary top level links to
 + Documentation
 + Blogs
 + Issues
 + Github
 + Eclipse
 + Webtide

It might also help if all pages displayed their Contents, even if mostly empty.

**Comment by jmcc0nn3ll** [comment]
I see what you are saying...the layout of these toc pages are currently treated differently if they are a 'website page' vs a 'documentation page'. 

I'll take a look.

**Comment by gregw** [comment]
Can the right hand side "Contents" menu be renamed to "Page Contents", so it is clear that it is not the contents of the documentation, but just the page you are looking at.
Then always have a left side navigation menu and it will be very clear.

**Comment by jmcc0nn3ll** [comment]
I think this is addressed now that the upper right menu is clearer and we have the Links dropdown. We can add to that as needed either directly to through another issue.
