### ISSUE TITLE
Home page needs more links less text

### ISSUE THREAD

**Issue by gregw** [jetty/jetty.website#31]
There are few links out from the [homepage](https://jetty.github.io/jetty.website/) to anywhere. There is one buried link to the documentation, but it is not very prominent.

The home page is our landing page and it has to be easy to navigate from. In fact the primary purpose of that page should be to navigate to other pages, few will read the text.   For example, I don't think we need two headings and a paragraph of text about how good our blogs are... but then have no links to the actual blogs.   Perhaps just have blogs in a left menu that go to the blogs without fanfare.

**Comment by jmcc0nn3ll** [comment]
This content has been on the Jetty homepage for eons now. I agree it can be updated. The intro paragraph and the table are either useful or not. On one hand, the homepage needs to say something about what this Jetty page someone landed on is all about...on the other hand, it should be a quick shunt to the things the person is interested in, 

We can develop a better page that fits the bill for both of these needs. If you have an example page that you like, it would be welcome, and I can adapt it to fit our needs.

RE: Blogs, we have the 6 or so tiles with the latest blogs rendering on the page (or they should be).

**Comment by gregw** [comment]
@jmcc0nn3ll on the current page, there are two menus:

1. top center has : Download; Documentation; Security Reports; Get Involved; Support
2. top right has: About; Tools; Contribute; Source code; Enter Bug;

So  we definitely want to clean that up. 

The text is fine, but you'd think the majority user arriving will be looking for links to one of:
 + Download
 + Documentation
 + Source Code
 + Support
 + Contributing
 + Security
 + Bug Reports

So I think those items need to be prominent links in a left menu like the Documentation.

We can have a right Contents (should we call it Page Contents) menu listing the subsections of the text on this page, but they need to have significantly different title to the left menu:
 + About Jetty
 + Why use Jetty
 + Who uses Jetty
 + History

**Comment by jmcc0nn3ll** [comment]
So... I am working on setting up a left menu for the normal website pages, but...

We can easily add dropdowns onto the nav menu of the main website, then they are available on all of the documentation pages as well instead of having to navigate back to the main site to then drill down into a left menu.

The Page Contents right side box is a context menu for the contents of the page you are currently look at, changing the context for that to something different is possible but I question that value....I think we should just focus on more links into the existing navigation menu, and maybe cleaning up the content of the existing pages as needed.

**Comment by gregw** [comment]
Wow, I just noticed the "Documentation, Support, Security, Community, Download"  in the top right!  Have they always been there, or have they just been added?

The "Page Contents" title really helps with making it clear what the right side box is about.  So I think we can rest on that one.

I find it hard to switch from the top right menus to the home/section menus on the left.... but at least they are there.
I'm wondering if all it really needs is that on the [entry page](https://jetty.github.io/jetty.website/index.html) is to have the "Documentation, Support, Security, Community, Download"  links in the same color/font as the top right, repeated directly under the Jetty logo.

If that could be  done, that would be good.  Eitherway, consider this one mostly done as the links are at least there... if not immediately apparent.   But once I found them, they are OK.

**Comment by jmcc0nn3ll** [comment]
Yes, those top right links have been there from day one. We can also make them dropdown on hover as well if we want to have more directly linkable.

I'll work on a linky section in the middle under the logo now.

**Comment by jmcc0nn3ll** [comment]
Actually, @gregw what do you think about the Links dropdown on stage.jetty.org now? I think it ought to be moved to the end but I think that works. I removed the link for Community because the content on that page is kinda just fluffy I think and the room is better used for this. Links seems to be a popular section title like this and its name implies it might take you off the website.

**Comment by gregw** [comment]
The problem is that now I've seen the top right menu, I always see it as I no longer have fresh eyes.

The links drop down is OK, but hard to think of the reason to put something in the top bar vs in the Links drop down.    Maybe having everything in the top right bar will make it more visible to fresh eyes?
Hmm but having too many items there makes the page go to the double sandwich menu button on narrow screens.    So the only thing I'd change is to make the links the rightmost and maybe move Download into it?

Oh Links is right most on entry page, but left most on other pages.  Rightmost everywhere please.

This is good enough to go.

**Comment by jmcc0nn3ll** [comment]
I think the Links is moving around from caching

I'll get a squared away tomorrow
