### ISSUE TITLE
Titles for Jetty-10, Jetty-11 and Jetty-12

### ISSUE THREAD

**Issue by gregw** [jetty/jetty.website#33]
The titles for the top level pages of Jetty-10, Jetty-11 and Jetty-12 should have the version number in the title. e.g on https://jetty.github.io/jetty.website/docs/jetty/10/index.html it is only apparently we are looking at Jetty-10 by the small selector top right and by reading the body of the first line. Put it in the title, so it will appear on the left menu, top of the page and tab/page title.

**Comment by jmcc0nn3ll** [comment]
I believe this can be achieved by updating the relevant guides once the PR's are merged. Talking with @mojavelinux tomorrow and we'll see if we can the PRs merged to make this change, or we can make the change in the current docs and have him regenerate the PRs (I would like to avoid making him regenerate the PRs as much as we have). This should be a quick fix either way.

ex. the following index.adoc can have a title of 'Jetty 10 Operations Guide'

https://github.com/jetty/jetty.project/blob/jetty-12.0.x/documentation/jetty-documentation/src/main/asciidoc/operations-guide/index.adoc

**Comment by mojavelinux** [comment]
This can be handled by the migration. I have updated the migration script and the resulting PRs.

And yes, this is the kind of customization you can do after the migration if it is needed in other places. I will state that it is customary in an Antora-based site (and the sites after which we modeled the software) to not proliferate the version all over the titles. But, if it's something you prefer, it can be added using the `{page-version}` attribute reference, as I have done.

```
[reftext=Operations Guide]
= Jetty {page-version} Operations Guide
```

See https://docs.antora.org/antora/latest/page/intrinsic-attributes/#page-attributes

**Comment by mojavelinux** [comment]
If you want the version to be absolutely everywhere, don't set the reftext, which is used for the navtitle and xrefs. But I find adding the version in all those places to be ridiculous, which is why I proposed limiting it to the page title itself.

**Comment by mojavelinux** [comment]
When a formal redesign is done, you can opt to make the documentation version more prominent. For example:

* https://docs.spring.io/spring-security/reference/
* https://openliberty.io/docs/latest/overview.html
* https://docs.hazelcast.com/hazelcast/5.4/
* https://docs.rudder.io/reference/8.1/index.html
* https://debezium.io/documentation/reference/2.6/index.html

We just don't do it that way in the default UI for reasons I have stated in the Antora project many times, the default UI is just a reference.

**Comment by jmcc0nn3ll** [comment]
Thanks, @mojavelinux. I think this partially addresses Greg's concern, but I suspect he is interested in a deeper distinction between versions throughout the pages. I have mixed feelings on it but it is something we'll iron out over time.

**Comment by gregw** [comment]
Actually I thinking just putting the version in the to level title probably would be enough (3 places.). It will then assist in the left menu as well

**Comment by gregw** [comment]
To be specific, it is only the following 3 pages that I think need the version added to their titles:
 + https://stage.jetty.org/docs/jetty/10/index.html
 + https://stage.jetty.org/docs/jetty/11/index.html
 + https://stage.jetty.org/docs/jetty/12/index.html

What is the plan for 12.1?    I think it should just become 12 and we do not maintain separate documentation for 12.0 vs 12.1   We should just say 12 rather than 12.x, so we have freedom to increment the dot without it being a big deal.

**Comment by jmcc0nn3ll** [comment]
@gregw see https://github.com/jetty/jetty.project/pull/11870 which should be able to be merged in an forward with no other changes required

**Comment by jmcc0nn3ll** [comment]
@gregw as for 12.1, I suspect this depends heavily on if 12.0 is going to be able to dead ended in the short term or not.
