### ISSUE TITLE
Review documentation search

### ISSUE THREAD

**Issue by sbordet** [jetty/jetty.website#34]
Currently, searching is present in the header of all pages, but I think it should be present only when we are in the documentation page (no point searching the documentation when you are in the "Support" page).

Also, currently searching e.g. for "http2" yields results for all 3 (in future 4) versions of Jetty: 10, 11 and 12.
Would it be possible to restrict the search to just the version we are looking at?

**Comment by jmcc0nn3ll** [comment]
this was updated so only jetty12 results are returned 

I am lukewarm on this but it can't be denied it will drive people towards 12
