### ISSUE TITLE
mvnw usage is not inherited

### ISSUE THREAD

**Issue by jmcc0nn3ll** [jetty/jetty.website#40]
19:55:18 [INFO] Running 'npx --offline antora --stacktrace --to-dir target/site --clean --fetch --extension @antora/collector-extension --extension lunr --extension jetty-downloads --extension register-asciidoctor-kroki --extension ./lib/router-extension.js --log-failure-level warn antora-playbook.yml' in /home/ubuntu/jetty.website
19:55:52 [INFO] [19:55:52.558] FATAL (antora): (@antora/collector-extension): Command not found: mvn install -ntp -B -Dcollector -Pfast -am -pl documentation/jetty in https://github.com/jetty/jetty.project (branch: jetty-10.0.x | start path: documentation/jetty)

I am working on getting the build running in a new env where jetty.org will be hosted and this mvnw usage is not inherited down into the underlying npx.

Not that I particularly expected it to be, but this does mean that mvn needs to be setup and we can't rely on the mvnw to work its magic.

**Comment by jmcc0nn3ll** [comment]
This is mostly an informational bug for you and @mojavelinux to be aware of, I don't know that there is a simple fixing this. Unless there is and I can be amazed! 👍

**Comment by mojavelinux** [comment]
The Jetty project doesn't itself use mvnw to my knowledge, which is why the collector command is configured the way it is. If it were, the command in antora.yml could be changed to mvnw. In that case, I would not expect it to be inherited, but rather to use the mvnw that is in that branch.

**Comment by jmcc0nn3ll** [comment]
awww i see, @olamy is this something we are interested in for jetty proper?

**Comment by olamy** [comment]
personally, I don't use `mvnw`, really. I'm happy with sdkman :)
Jenkins can download Maven distro from our CI Nexus. If we add mvnw this will need to be downloaded from Maven central.
BTW I can add some setup in the GHA to generate `mvnw` so we are sure a good version is used and not depends on some random GHA
