### ISSUE TITLE
Update Documentation page

### ISSUE THREAD

**Issue by jmcc0nn3ll** [jetty/jetty.website#59]
Factor in the changes from:

https://github.com/jetty/jetty.project/pull/12194

**Comment by sbordet** [comment]
> As it stands the content on this page really thin and if we remove the split links to the operations guide and the programming guide it will be even thinner.

That's the goal.

I want as much as possible in the documentation.

The website pages should just be a small glue that points to the documentation.

**Comment by jmcc0nn3ll** [comment]
In principle, yes, but this page is just a thin extra click-through page, which I think we want to avoid.

I'll do the basic we talked about and see how it looks.

**Comment by jmcc0nn3ll** [comment]
deployed
